### ISSUE TITLE
Compile under FreeBSD

### ISSUE THREAD

**Issue by Mikanoshi** [ShieldCoin/SHIELD#10]
# Errors while compiling headless node under FreeBSD

## OS/version

OS: FreeBSD 11.1-RELEASE-p1 amd64

VERSION: SHIELD 2.3.0.0

## Problem summary
Errors when source is being compiled under FreeBSD. Both with GCC and clang.
I was never able to compile nodes based on new bitcoin base using GCC, so next steps are for clang (it's the only default compiler on FreeBSD).

## Steps to reproduce errors
./autogen.sh
./configure --without-gui --without-miniupnpc --with-boost-libdir=/usr/local/lib BDB_CFLAGS="-I/usr/local/include/db48/" BDB_LIBS="-L/usr/local/lib/db48/ -ldb_cxx-48" LDFLAGS="-L/usr/local/lib/db48/ -lexecinfo" CPPFLAGS="-I/usr/local/include/db48/ -O2" CC=clang CXX=clang++
gmake

## Errors and fixes
- ``error: redefinition of 'uint32_t le32dec(const void*)'``
le32enc(), le32dec(), be32enc(), be32dec() are already defined in sys/endian.h, so they shouldn't be redefined
- ``./serialize.h:856:10: error: class member cannot be redeclared
    void insert(iterator it, std::vector<char>::const_iterator first, std::vector<char>::const_iterator last)
         ^
./serialize.h:843:10: note: previous declaration is here
    void insert(iterator it, const_iterator first, const_iterator last)``
insert() method in serialize.h is defined twice (one definition is under #ifndef MAC_OSX), they both are active on FreeBSD, so one should have a better condition applied.
- ``  CXXLD    SHIELDd
libbitcoin_util.a(libbitcoin_util_a-util.o): In function `LogStackTrace()':
/usr/src/crypto/shield/src/src/util.cpp:1010: undefined reference to `backtrace'
/usr/src/crypto/shield/src/src/util.cpp:1011: undefined reference to `backtrace_symbols_fd'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)``
execinfo lib should be added (-lexecinfo in LDFLAGS above)

**Comment by ShieldCoin** [comment]
`error: redefinition of 'uint32_t le32dec(const void*)'` seems to be common and unsolved afaik, I will need more details if I want to attempt a fix: https://github.com/litecoin-project/litecoin/issues/379

I've tried fixing the serialize error in the latest commit

Last one is probably because of a un-included path from libexecinfo, try adding `-L/path/to/libexecinfo` to LDFLAGS

**Comment by Mikanoshi** [comment]
Yes, enc/dec are defined in most of the wallets, I just remove them :)
But `__FreeBSD__` condition should work too.
Also had to add `#include <sys/endian.h>` to scrypt-sse2.cpp

**Comment by ShieldCoin** [comment]
ah I see, nice, I'll add it for freebsd
