### ISSUE TITLE
this is just a clone of verge, without all the privacy features.

### ISSUE THREAD

**Issue by justinvforvendetta** [ShieldCoin/SHIELD#11]
# [ISSUE TITLE]

## OS/version

OS: [OS]

VERSION: [Type and VersionNumber]

## Problem summary
[Summary]

## Possible Step to Reproduce error
[Reproduction Steps]

**Comment by ShieldCoin** [comment]
cool cool

**Comment by ShieldCoin** [comment]
Btw tor nodes this friday

**Comment by blathursby** [comment]
When is wraith releasing Justin?
