### ISSUE TITLE
2 daemons with different algo

### ISSUE THREAD

**Issue by Ryuspb** [ShieldCoin/SHIELD#13]
Hello!

How to run 2 daemons via one linux server for x17 and blake2s algo?
Maybe there are some key like "-c" or another?

**Comment by ShieldCoin** [comment]
To run 2 daemons you need to have a different data directory, this can be done by having 2 seperate linux accounts (one for each daemon). Make sure to run them with a different rpcport and port option

Example configs are:
~/.SHIELD/SHIELD.conf (in first user)
```
rpcuser=XSH1
rpcpassword=Don'tusethispassword
rpcport=20103
port=21103
daemon=1
algo=x17
```
~/.SHIELD/SHIELD.conf (in second user)
```
rpcuser=XSH2
rpcpassword=Don'tusethispasswordeither
rpcport=20104
port=21104
daemon=1
algo=blake2s
```

**Comment by Ryuspb** [comment]
Okey! But maybe I can use key --datadir ? Its works?

1). ./SHIELDd --datadir /root/.SHIELD_1/SHIELD.conf 
and 
2). ./SHIELDd --datadir /root/.SHIELD_2/SHIELD.conf

**Comment by ShieldCoin** [comment]
Yes that should work although you have to point to the dir like so:
`./SHIELDd --datadir /root/.SHIELD_1/`

**Comment by Ryuspb** [comment]
./SHIELDd --datadir /root/.SHIELDB
Error: Specified directory does not exis

**Comment by Ryuspb** [comment]
... also I tried to start the daemon from another user

xshb@bsod:~/.SHIELD$ SHIELDd
SHIELD server starting
xshb@bsod:~/.SHIELD$ SHIELD: Failed to listen on any port. Use -listen=0 if you want this.

**Comment by Ryuspb** [comment]
Fixed!
