### ISSUE TITLE
importprivkey didn't work

### ISSUE THREAD

**Issue by mycall** [ShieldCoin/SHIELD#14]
# importprivkey didn't work

## OS/version

OS: Windows 10

VERSION: Professional build 1709

## Problem summary
Following the steps listed out @ https://github.com/ShieldCoin/SHIELD/wiki/SHIELDqt-Import-Keys, I executed in the console "importprivkey <priv-key>" for several private keys exported from Electrum-XSH wallet. I don't see the transactions from the other wallet.   

I assume the private keys were imported correctly, but the other wallet's receive addresses aren't imported.  How do I import the addresses from the other wallet (pub/priv keys for each XSH address)?   There are lots of options with help in console but I don't know the process to transfer addresses.

**Comment by ShieldCoin** [comment]
Are you fully synced (up to ~490k blocks in debug window)? and do you see the addresses in the receive tab?

**Comment by mycall** [comment]
Yes, the Qt client is fully synced but I don't see the addresses in the receive coins tab (I see them in the address book).  Pressing the New Address button in Receive coins tab doesn't allow me to enter in the receive address from the other wallet (I guess that is by design).

I'm obviously missing something simple here.  Maybe I can import the wallet.dat from the Electrum-XSH client into the Qt client?
