### ISSUE TITLE
Android wallet not connecting

### ISSUE THREAD

**Issue by kschroed** [ShieldCoin/SHIELD#17]
# Android connection

## OS/version

OS: Android
VERSION: 7-ish

## Problem summary
[Summary]
Unable to get a connection on Android Wallet or Electrum Wallet on Windows.
## Possible Step to Reproduce error
Install wallet
run wallet

**Comment by kschroed** [comment]
I was able to fix the Windows Electrum Wallet but connecting to a different server, but the Android Wallet still fails to connect, and not sure how to export my keys from that wallet either, so kind of in limbo with accessing my coins.

**Comment by mimatthe** [comment]
Seeing the same issue with the Android wallet, No Connection since this morning.

**Comment by IwraStudios** [comment]
I think there was going to be an update for the android with the new electrum server

**Comment by ShieldCoin** [comment]
There will be an update to include our new servers

**Comment by kolcsarmeister** [comment]
The Shieldcoin android app is not connected to the hálozathoz. What can I do to get it to work, now it's got shield coin but I cannot access it

**Comment by ShieldCoin** [comment]
There already is an update, just redownload it from the website
