### ISSUE TITLE
BitDefender has tagged this version with Trojan Gen:Variant.Razy.393423 and has quarantined the .exe

### ISSUE THREAD

**Issue by DeepM1** [ShieldCoin/SHIELD#2]
BitDefender has tagged this version with Trojan Gen:Variant.Razy.393423 and has quarantined the .exe
Please advise.  Thank you.

**Comment by DeepM1** [comment]
BitDefender has tagged this version with Trojan Gen:Variant.Razy.393423 and has quarantined the .exe
Please advise.  Thank you.
Also, I can't current reach https://shieldcore.org/en/contact/ to pass this information on to there.

**Comment by DeepM1** [comment]
No problem so far with the "stand alone" version

**Comment by ShieldCoin** [comment]
Hey @DeepM1 
This is a common detection with altcoins using mining algorithms. There shouldn't be a problem with it. Can you tell me which version you used?
