### ISSUE TITLE
please test mac OSX dmg file

### ISSUE THREAD

**Issue by pyramation** [ShieldCoin/SHIELD#24]
# OSX dmg build

https://www.amazon.com/clouddrive/share/h1vQLfbI8WLmsd9sTGpCUV32hiH5KwbWoDwo5ANOVOO

for extra security, check the hash please:

```
$ shasum SHIELD-Qt.dmg
352d488e5bcdf30ea002ec0076c8a8fd1894ff3e  SHIELD-Qt.dmg
```

Let's try and test this on as many as we can, below I created a checklist of the most recent OSX versions

# versions it works on

- [ ] high sierra
- [ ] el capitan
- [ ] yosemite
- [ ] mavericks

**Comment by pyramation** [comment]
let's try this, hopefully it packages `boost`

https://www.amazon.com/clouddrive/share/OZmAjcZCAwQgYIbdNIGSDEHbZzD9l04nIg8B5ZlwUVs

```
$ shasum SHIELD-Qt.dmg
ee6bfc6ee4bc36eef5b62d04ca7b83f4255405b7  SHIELD-Qt.dmg
```

**Comment by pyramation** [comment]
OK, let's try this

https://www.amazon.com/clouddrive/share/0WBNojwXgHcQcOA6Q0A8meEoyQqCRdEoR43oOSsGQST

```
$ shasum SHIELD-Qt.dmg
7d4cc05edf882aa3bf10e7cc383c5f7833d43b90  SHIELD-Qt.dmg
```

**Comment by pyramation** [comment]
last one!

https://www.amazon.com/clouddrive/share/FgcnOhhqfF2aEBKLPngwmR0oGtr3pwJzMvofJiSievX

```
$ shasum SHIELD-Qt.dmg
06e00c385b3dee9c42616fd0fe50232ce0b540ee  SHIELD-Qt.dmg
```

**Comment by ShieldCoin** [comment]
Closing for now
