### ISSUE TITLE
Unable to start shield wallet

### ISSUE THREAD

**Issue by konsacz** [ShieldCoin/SHIELD#27]
# [Unable to start shield wallet]

## OS/version

OS: [Ubuntu]

VERSION: [16.04 LTS]

## Problem summary
[I'm unable to launch wallet. Command SHIELD-qt starting process but I get pop Failed to listen on any port. Use -listen=0 if you want this.
My debug.log shows
SHIELD version v2.3.0.0-325e2c7-funky-beta (2018-01-11 22:08:55 +0100)
Using OpenSSL version OpenSSL 1.0.2g  1 Mar 2016
Startup time: 30.01.2018 21:21:05
Default data directory /home/konrad/.SHIELD
Default mining hash algorithm: scrypt
Used data directory /home/konrad/.SHIELD
scrypt: using scrypt-sse2 as detected.
dbenv.open LogDir=/home/konrad/.SHIELD/database ErrorFile=/home/konrad/.SHIELD/db.log
Unable to bind to [::]:21103 on this computer. SHIELD is probably already running.
Unable to bind to 0.0.0.0:21103 on this computer. SHIELD is probably already running.
trying connection 188.226.178.216:21103 lastseen=114.0hrs
connected 188.226.178.216:21103
send version message: version 90005, blocks=516667, us=91.223.212.116:21103, them=188.226.178.216:21103, peer=188.226.178.216:21103
socket closed
disconnecting node 188.226.178.216:21103
trying connection 103.18.40.125:21103 lastseen=393707.6hrs
connect() failed after select(): No route to host
trying connection 104.131.144.82:21103 lastseen=393707.6hrs
connect() failed after select(): Connection refused
trying connection 138.197.68.130:21103 lastseen=393707.6hrs
connect() failed after select(): Connection refused
trying connection 144.76.167.66:21103 lastseen=393707.6hrs
connect() failed after select(): Connection refused
trying connection 152.186.36.86:21103 lastseen=393707.6hrs]

## Possible Step to Reproduce error
[Reproduction Steps]

**Comment by ShieldCoin** [comment]
Seems like something is already using the SHIELD p2p port try running `netstat -lnp` to see what is using it

The port needs to be free, you can also change it by setting `port=random_port_number` for example `port=8085` in ~/. SHIELD/SHIELD.conf

-------- Original Message --------

**Comment by konsacz** [comment]
It seems that I opened SHIELDd firstly and that was an issue, however after restart still I can't open wallet. When I type in console SHIELD-qt it shows me 
![zrzut ekranu z 2018-01-14 23-58-06](https://user-images.githubusercontent.com/35975685/35594124-5d024130-0612-11e8-9935-4538e3f242c6.png) and it doesn't proceed further.
debug

SHIELD version v2.3.0.0-325e2c7-funky-beta (2018-01-11 22:08:55 +0100)
Using OpenSSL version OpenSSL 1.0.2g  1 Mar 2016
Startup time: 30.01.2018 21:57:33
Default data directory /home/konrad/.SHIELD
Default mining hash algorithm: scrypt
Used data directory /home/konrad/.SHIELD
scrypt: using scrypt-sse2 as detected.
dbenv.open LogDir=/home/konrad/.SHIELD/database ErrorFile=/home/konrad/.SHIELD/db.log
Bound to [::]:21103
Bound to 0.0.0.0:21103
Loading block index...
Opening LevelDB in /home/konrad/.SHIELD/txleveldb
Transaction index version is 70509
Opened LevelDB successfully
SHIELD: Cannot obtain a lock on data directory /home/konrad/.SHIELD.  SHIELD is probably already running.
Flush(false) db not started
StopNode()
Flushed 0 addresses to peers.dat  85ms
Flush(true) db not started
SHIELD exited

**Comment by ShieldCoin** [comment]
You need to let it load for a while can take up to 5 minutes depending on your hardware, it also says you already have a SHIELDd or SHIELD-qt running so you might want to check your processes with `ps aux`

**Comment by konsacz** [comment]
Ok It's working. I didn't knew that I should wait min 5min. Thank you!
