### ISSUE TITLE
wallet and daemon won't start

### ISSUE THREAD

**Issue by boo50** [ShieldCoin/SHIELD#4]
# [Wallet and daemon won't start]

## OS/version

OS: Ubuntu Gnome 16.04

## Problem summary
after compiling a walet and daemon, can;t start them

SHIELD: Error initializing database environment /home/user/.SHIELD! To recover, BACKUP THAT DIRECTORY, then remove everything from it except for wallet.dat.

can't get it working after removing everything from that directory, always same error

**Comment by ShieldCoin** [comment]
Do you have the latest: libdb-dev libdb++-dev
Also, did you use `./configure --with-incompatible-bdb`
And lastly, did you try running it with sudo permissions

**Comment by boo50** [comment]
Yes, I've latest  libdb-dev libdb++-dev, use exaclty thesame code and also tried to run with sudo, no luck, always same error.
I've build prev. version 1.0 with no problems and it works on the same machine.

**Comment by ShieldCoin** [comment]
Strange, what does it say in ~/.SHIELD/debug.log(post on pastebin if it's long)

**Comment by boo50** [comment]
SHIELD version v2.1.0.0-fdd2d9f-funky-beta (2017-10-06 23:53:53 +0200)
Using OpenSSL version OpenSSL 1.0.2g  1 Mar 2016
Startup time: 14.10.2017 06:37:55
Default data directory /home/user/.SHIELD
Default mining hash algorithm: scrypt
Used data directory /home/user/.SHIELD
scrypt: using scrypt-sse2 as built.
dbenv.open LogDir=/home/user/.SHIELD/database ErrorFile=/home/user/.SHIELD/db.log
ERROR: CDB() : error Invalid argument (22) opening database environment

All files in ~/.SHIELD are read only owned by root, in all other crypto wallets I've full access to the similar files.

**Comment by ShieldCoin** [comment]
Refering to this issue https://github.com/litecoin-project/litecoin/issues/209
It seems to be that the local version of libdb(berkley db) is not the same as the one you compiled with
make sure you have the right libraries installed and that they are the libraries being used,
and remove any unneeded/incompatible libdb versions
